### PR TITLE
bounding_box_rectangle_optimizations

### PR DESCRIPTION
**Pull request by damooo**
customization of oa:FragmentSelector to easily query, based on geometric requirements.

### CODE REVIEW

**Comment by shashikiranraifox** [comment]
@damooo  after the above changes were made, have you verified the following:
- that the user is able to create/edit/delete/view normal shape annotations[rectangle, Circle etc ]

**Comment by damooo** [comment]
yes anna. they are working. but i am closing pull request, will open with another small change

**Comment by damooo** [comment]
Anna, mongo geoJson only supports coordinates between -180 to 180, hence it is not possible to formulate precise generic query for getting rectangles which are inside a polygon. though we can get those rect annos whose having x, y greater than bounding box, and w, h less than that of bounding box independently, we cannot combine both for getting through query. so we should compute them from local machine only, instead of api call. this pull request i am reopening.

**Comment by shashikiranraifox** [comment]
Closed this after confirmation by that legacy shape annotations are working.
@damooo  please do summarize what exactly these changes are doing?

**Comment by damooo** [comment]
yes anna, legacy ones are working.
changes:

1. purge previous repoName redundancies.
2. at the time of creating annotation, we add rectangle details in accessible manner like
 ```
{
    "selector": {
      "default": {
        "jsonClass": "FragmentSelector",
        "value": "xywh=13,45,120,56",
        "rectangle": {
          "jsonClass": "WrapperObject",
          "x": 13,
          "y": 45,
          "w": 120,
          "h": 56
        }
      }
    }
}
```
along with standard oa:FragmentSelector's "value", we are attaching "rectangle" value, too so that, at the time of querying we can query over x, y, w, h. or we can directly use them as client instead of marshalling 'value' ourselves each time.

**Pull request merged**
